logging:
  file:
    name: /appl/logs/desafio-communication-scheduling
  level:
    org:
      apache:
        commons:
          httpclient: DEBUG  #Log das operações internas do cliente HTTP
    com.desafio.scheduling.communication: TRACE

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/db
    driverClasName: org.h2.Driver
    username: user
    password: password
  main:
    allow-bean-definition-overriding: true