CREATE TABLE communication_scheduling (
	ID INT NOT NULL AUTO_INCREMENT,
	CREATION_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SCHEDULE_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PHONE_NUMBER varchar(20),
	EMAIL varchar(100),
	SEND_TYPE INT NOT NULL,
	MESSAGE varchar(100) NOT NULL,
	STATUS INT,
	STATUS_DESCRIPTION varchar(100),
	PRIMARY KEY (ID)
 );
